// Code generated by Prismic. DO NOT EDIT.

import CallToAction from "./CallToAction";
import Faq from "./Faq";
import Features from "./Features";
import Hero from "./Hero";
import LogoCloud from "./LogoCloud";

export const components = {
  call_to_action: CallToAction,
  faq: Faq,
  features: Features,
  hero: Hero,
  logo_cloud: LogoCloud,
};
