// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  faq: dynamic(() => import("./Faq")),
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  logo_cloud: dynamic(() => import("./LogoCloud")),
};
